sudo: required
language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
install: 
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq unixODBC ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq unixODBC-dev  ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq libmysqlclient-dev   ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq libcurl4-gnutls-dev  ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq libssl-dev  ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install unixodbc ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mysql-connector-c ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install allegro ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/versions/qt55 ; fi
 
script: 
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd src && sudo ./buildgcccomplete.sh ; fi
# - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ../extensions/ringallegro && ./gencode.sh && ./buildgcc.sh ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ../extensions/ringallegro && ./gencode.sh  ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ../ringqt && ./gencode.sh && ./buildgcc.sh ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd src && ./buildclangcomplete.sh ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd ../extensions/ringallegro && ./gencode.sh && ./buildclang.sh ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd ../ringqt && ./gencode.sh && ./buildclang.sh ; fi
 
notifications:
 email: false